- job:
    name: zun-tempest-py35-docker-sql-rocky
    parent: zun-tempest-py35-docker-sql
    nodeset: openstack-single-node-xenial
    override-checkout: stable/rocky
    vars:
      branch_override: stable/rocky

- job:
    name: zun-tempest-py35-docker-sql-stein
    parent: zun-tempest-py35-docker-sql
    nodeset: openstack-single-node-bionic
    override-checkout: stable/stein
    vars:
      branch_override: stable/stein

- job:
    name: zun-tempest-py3-docker-sql-train
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    vars:
      branch_override: stable/train

- job:
    name: zun-tempest-py3-docker-sql-ussuri
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-bionic
    override-checkout: stable/ussuri

- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        - zun-tempest-py3-docker-sql
        - zun-tempest-py35-docker-sql-rocky
        - zun-tempest-py35-docker-sql-stein
        - zun-tempest-py3-docker-sql-train
        - zun-tempest-py3-docker-sql-ussuri
        - zun-tempest-multinode-docker-sql
    gate:
      queue: zun
      jobs:
        - zun-tempest-py3-docker-sql
        - zun-tempest-py35-docker-sql-rocky
        - zun-tempest-py35-docker-sql-stein
        - zun-tempest-py3-docker-sql-train
        - zun-tempest-py3-docker-sql-ussuri
