- job:
    name: zun-tempest-py3-docker-sql-2023-2
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.2

- job:
    name: zun-tempest-py3-docker-sql-2024-1
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.1

- job:
    name: zun-tempest-py3-docker-sql-2024-2
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.2

- project:
    queue: zun
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        - zun-tempest-py3-docker-sql
        - zun-tempest-py3-docker-sql-2023-2
        - zun-tempest-py3-docker-sql-2024-1
        - zun-tempest-py3-docker-sql-2024-2
        - zun-tempest-multinode-docker-sql
    gate:
      jobs:
        - zun-tempest-py3-docker-sql
