- job:
    name: zun-tempest-py3-docker-sql-ussuri
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-bionic
    override-checkout: stable/ussuri

- job:
    name: zun-tempest-py3-docker-sql-victoria
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-focal
    override-checkout: stable/victoria

- job:
    name: zun-tempest-py3-docker-sql-wallaby
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby

- job:
    name: zun-tempest-py3-docker-sql-xena
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena

- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        - zun-tempest-py3-docker-sql
        - zun-tempest-py3-docker-sql-ussuri
        - zun-tempest-py3-docker-sql-victoria
        - zun-tempest-py3-docker-sql-wallaby
        - zun-tempest-py3-docker-sql-xena
        - zun-tempest-multinode-docker-sql
    gate:
      queue: zun
      jobs:
        - zun-tempest-py3-docker-sql
        - zun-tempest-py3-docker-sql-ussuri
        - zun-tempest-py3-docker-sql-victoria
        - zun-tempest-py3-docker-sql-wallaby
        - zun-tempest-py3-docker-sql-xena
