- job:
    name: zun-tempest-py3-docker-sql-yoga
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga

- job:
    name: zun-tempest-py3-docker-sql-zed
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-focal
    override-checkout: stable/zed

- job:
    name: zun-tempest-py3-docker-sql-2023-1
    parent: zun-tempest-py3-docker-sql
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.1

- project:
    queue: zun
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        - zun-tempest-py3-docker-sql
        - zun-tempest-py3-docker-sql-yoga
        - zun-tempest-py3-docker-sql-zed
        - zun-tempest-py3-docker-sql-2023-1
        - zun-tempest-multinode-docker-sql
    gate:
      jobs:
        - zun-tempest-py3-docker-sql
        - zun-tempest-py3-docker-sql-yoga
        - zun-tempest-py3-docker-sql-zed
        - zun-tempest-py3-docker-sql-2023-1
